"""changed some tables

Revision ID: 645cb6297910
Revises: fcb5d7fa789e
Create Date: 2022-10-14 14:44:16.595877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '645cb6297910'
down_revision = 'fcb5d7fa789e'
branch_labels = None
depends_on = None


def upgrade():
    '''
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trs398_electrons', sa.Column('temp_press_e', sa.Integer(), nullable=True))
    op.add_column('trs398_electrons', sa.Column('pdd_data_e', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'trs398_electrons', 'temp_press', ['temp_press_e'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'trs398_electrons', 'pdd_data_electrons', ['pdd_data_e'], ['id'], ondelete='CASCADE')
    op.drop_column('trs398_electrons', 'm_Rp')
    op.drop_column('trs398_electrons', 'm_R50')
    op.drop_column('trs398_electrons', 'press')
    op.drop_column('trs398_electrons', 'temp')
    op.add_column('trs398_photons', sa.Column('temp_press_p', sa.Integer(), nullable=True))
    op.add_column('trs398_photons', sa.Column('pdd_data_p', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'trs398_photons', 'temp_press', ['temp_press_p'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'trs398_photons', 'pdd_data_photons', ['pdd_data_p'], ['id'], ondelete='CASCADE')
    op.drop_column('trs398_photons', 'm_pdd10')
    op.drop_column('trs398_photons', 'm_tpr')
    op.drop_column('trs398_photons', 'press')
    op.drop_column('trs398_photons', 'temp')

    '''
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trs398_photons', sa.Column('temp', sa.FLOAT(), nullable=False))
    op.add_column('trs398_photons', sa.Column('press', sa.FLOAT(), nullable=False))
    op.add_column('trs398_photons', sa.Column('m_tpr', sa.FLOAT(), nullable=True))
    op.add_column('trs398_photons', sa.Column('m_pdd10', sa.FLOAT(), nullable=True))
    op.drop_constraint(None, 'trs398_photons', type_='foreignkey')
    op.drop_constraint(None, 'trs398_photons', type_='foreignkey')
    op.drop_column('trs398_photons', 'pdd_data_p')
    op.drop_column('trs398_photons', 'temp_press_p')
    op.add_column('trs398_electrons', sa.Column('temp', sa.FLOAT(), nullable=False))
    op.add_column('trs398_electrons', sa.Column('press', sa.FLOAT(), nullable=False))
    op.add_column('trs398_electrons', sa.Column('m_R50', sa.FLOAT(), nullable=True))
    op.add_column('trs398_electrons', sa.Column('m_Rp', sa.FLOAT(), nullable=True))
    op.drop_constraint(None, 'trs398_electrons', type_='foreignkey')
    op.drop_constraint(None, 'trs398_electrons', type_='foreignkey')
    op.drop_column('trs398_electrons', 'pdd_data_e')
    op.drop_column('trs398_electrons', 'temp_press_e')
    # ### end Alembic commands ###
