"""electrons trs-398 table modified

Revision ID: 882c95a7303a
Revises: 6e21e4c342f5
Create Date: 2022-11-10 02:21:02.212664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '882c95a7303a'
down_revision = '6e21e4c342f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trs398_electrons', schema=None) as batch_op:
        batch_op.drop_column('b_dose_ref')
        batch_op.drop_column('b_pdiff')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trs398_electrons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('b_pdiff', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('b_dose_ref', sa.FLOAT(), nullable=True))

    # ### end Alembic commands ###
